FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY KeyCloakTest/KeyCloakTest.csproj KeyCloakTest/
RUN dotnet restore KeyCloakTest/KeyCloakTest.csproj

COPY . .
RUN dotnet publish KeyCloakTest/KeyCloakTest.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "KeyCloakTest.dll"]
